### ISSUE TITLE
Wiki entry: Python Protocols

### ISSUE THREAD

**Issue by CR1337** [BP2022-AP1/bp2022-ap1#103]
I have to write a wiki article about python protocols in order to clarify their usage to other team members.

## Description

We need a wiki entry that explains the usage of python protocols and how we will use them for our interfaces. It should also specify the conventions for how to use it in the context of this project.

**Comment by CR1337** [comment]
Now we have some explanation about protocols in our Wiki. I found it would be a good fit in the Architecture section:
https://github.com/BP2022-AP1/bp2022-ap1/wiki/Architecture/_edit#class-interfaces-using-python-protocols

**Comment by CR1337** [comment]
Here the correct Link:
https://github.com/BP2022-AP1/bp2022-ap1/wiki/Architecture#class-interfaces-using-python-protocols

**Comment by antonykamp** [comment]
can be closed?
