### ISSUE TITLE
Collect needed configuration classes for `DataScience` component

### ISSUE THREAD

**Issue by antonykamp** [BP2022-AP1/bp2022-ap1#113]
## User stories
As a developer of the REST API I want know which configuration classes are available for the `DataScience` component in order to add endpoints and tables.

## Wiki
- https://github.com/BP2022-AP1/bp2022-ap1/wiki/Architecture#database-class-diagram

## Acceptance Criteria
- [ ] Collect needed configuration classes
- [ ] Collect interaction and architecture between datascience component, results and run 
- [ ] update database class architecture

**Comment by LucasDerReisende** [comment]
Not planned, since data science will not use configuration classes
