### ISSUE TITLE
Remove `interfaces.py`

### ISSUE THREAD

**Issue by antonykamp** [BP2022-AP1/bp2022-ap1#128]
## User stories
As a developer I don't  want use Python Protocols. Instead I want to use normal classes as interfaces in the components.
Therefore, we have to (re)move the the Protocols and the `interfaces.py`file.

## Acceptance Criteria
- [ ] ~~(re)Moved content of `interfaces.py` into folder of component as normal classes~~
- [ ] remove `interfaces.py`

**Comment by CR1337** [comment]
The "normal classes" should be responsibility of the corresponding component owners.
