### ISSUE TITLE
Add table `Schedule`

### ISSUE THREAD

**Issue by antonykamp** [BP2022-AP1/bp2022-ap1#140]
## User stories
As a user I want to specify schedules in the spawner configuration and reuse it in order to define trains departures.

## Acceptance Criteria
- [x] Create table `Schedule` with peewee and marshmellow, without migration and foreign keys
- [x] add class to table-list in constants.py

**Comment by CR1337** [comment]
I will also add a table `TrainSchedule` that inherits from `Schedule`.

Also because a `Schedule` cannot exist without a `Strategy` I will also implement `Strategy` here.

**Comment by antonykamp** [comment]
> I will also add a table TrainSchedule that inherits from Schedule.
> Also because a Schedule cannot exist without a Strategy I will also implement Strategy here.

You can do that of course 😄
