### ISSUE TITLE
Bug: Docstrings not enforced everywhere

### ISSUE THREAD

**Issue by Lietze** [BP2022-AP1/bp2022-ap1#144]
## Problem Description

1. The CI and local linters don't detect missing docstrings in some Modules. Examples are: `route_controller.py`, `fault_injector.py` and everything in the `fault_types` directory.
2. Linters should find those missing docstrings in the same way they do in other Modules.
3. Developers can no longer rely on the linters in the same way.

## Steps For Reproduction

1. first go to  `route_controller.py`, `fault_injector.py` or anything in the `fault_types` directory
2. delete any or all docstrings you want
3. run `poe lint`
4. missing docstrings will not be detected

**Comment by instant-sky** [comment]
This effects not only docstrings. The reason for this are missing `__init__.py` files in the corresponding directories.
