### ISSUE TITLE
Diagramm for the data models used by the interlocking component

### ISSUE THREAD

**Issue by Lietze** [BP2022-AP1/bp2022-ap1#244]
I have to build a diagramm of all datamodels used by the interlocking component in order to know how to translate between the models (which ids are the same etc.).

## Wiki-Reference
- [Where the diagramm will be.](https://github.com/BP2022-AP1/bp2022-ap1/wiki/Interlocking-Component)

## Description
The relations between Yaramo, the internal model of the interlocking and the data model implemented by us (which are the objects from SUMO) need to be considered.

**Comment by SaturnHafen** [comment]
Would you mind adding a background to the diagram, it is partially hard to read. Alternatively, recreate it using mermaid. If you choose to keep the `drawio` file, please add the source file to the repo/wiki as well. Additionally, you are missing the traci-wrapper (or is that intentionally?)
Other than that: it looks pretty good

**Comment by Lietze** [comment]
Thank you for the feedback. 
I initially tried to use mermaid, but it did not like lines like "id = "route_{yaramo_route.start_signal.name,upper()}-{yaramo_route.end_signal.name,upper()}" for syntax reasons. I didn't really try to fix it, because in this case I also like to place the classes myself and have arrows from specific attributes. 
I used Lucidchart and for the export of a file there are three options: Lucidspark, Visio (VSDX) or Visio 2010 (VDX). Do you know which of these can be easily imported into drawio? I would upload that file then.
Also, I'm adding the traci-wrapper, although it may still be subject to change. Feedback to that will be appreciated.

**Comment by SaturnHafen** [comment]
You could link the document (read-only) under the wiki export

**Comment by Lietze** [comment]
This has been aproved by @SaturnHafen  but it may have to be updated in the future, as it is planed for the nodes and the tracks in the Traci-Wrapper to know each other.
