### ISSUE TITLE
Add `null=True` and remove `null=False` in ScheduleConfiguration

### ISSUE THREAD

**Issue by antonykamp** [BP2022-AP1/bp2022-ap1#265]
## User stories
As a developer of the ScheduleConfiguration I want to make the fields
- train_schedule_train_type,
- regular_strategy_start_tick and
- regular_strategy_frequency
optional.

## Acceptance Criteria
- [x] Add `null=True` to train_schedule_train_type, , regular_strategy_start_tick and regular_strategy_frequency
- [x] Remove `null=False` everywhere where it's not needed

**Comment by CR1337** [comment]
That was already done in a previous PR

**Comment by CR1337** [comment]
Therefore closed.
