### ISSUE TITLE
MoSCoW the interlocking Component

### ISSUE THREAD

**Issue by Lietze** [BP2022-AP1/bp2022-ap1#290]
I have to prioritise all the tings I could do in the interlocking component in order to be able to work toward a clear goal and request help if needed.

## (Wiki) References
- [Where it will be.](https://github.com/BP2022-AP1/bp2022-ap1/wiki/Interlocking-Component)

**Comment by SaturnHafen** [comment]
Something is wrong here:
> set fahrstrassen when when called (for the first fahrstrasse)

Do you mean *caching*?
> chashing

You might want to add something like
> set fahrstrassen according to fahrplan

as a *must-have*

In general, it looks like a sensible prioritization. I don't remember if we ditched something else already?

**Comment by Lietze** [comment]
I corrected some spelling mistakes. I will talk about this in the next meeting to get some more input.
