### ISSUE TITLE
Refactor Yaramo

### ISSUE THREAD

**Issue by antonykamp** [BP2022-AP1/bp2022-ap1#296]
## User stories
As a developer that generates the sumo configuration files with yaramo, I want that yaramo assigns the "Anschlüsse" correctly to have a correct railway network at the end.

## Acceptance Criteria
- [x] https://github.com/simulate-digital-rail/yaramo/issues/40
- [x] https://github.com/simulate-digital-rail/orm-importer/issues/54
- [x] https://github.com/simulate-digital-rail/planpro-importer/issues/11
- [x] https://github.com/simulate-digital-rail/cli-importer/issues/3
- [x] https://github.com/simulate-digital-rail/track-signal-generator/issues/9
- [x] https://github.com/simulate-digital-rail/yaramo/issues/41
- [x] https://github.com/simulate-digital-rail/interlocking-exporter/issues/3 (after ORM importer, on ice 🥶 )

**Comment by antonykamp** [comment]
How can we review this? What do you recommend? :)  @SaturnHafen

**Comment by antonykamp** [comment]
Should we just close it? :)

**Comment by SaturnHafen** [comment]
I guess so
