### ISSUE TITLE
```spawn_train``` retruns a boolean signaling if spawning the train was successful

### ISSUE THREAD

**Issue by Lietze** [BP2022-AP1/bp2022-ap1#350]
## User stories
As a the spawner I want to know if spawning the train was successful in order to try again next tick if it was not.

## Dependencies
Depends on: 
 - #348 

## Acceptance Criteria
- [ ] ```spawn_train``` returns ```True``` if spawning the train was successful
- [ ] if ```set_spawn_route``` returns ```None``` then ```spawn_train``` returns ```False```, because the fahrstrasse could not be set

**Comment by SaturnHafen** [comment]
This was already completed here: #11
