### ISSUE TITLE
Refractor Railway Route Generator

### ISSUE THREAD

**Issue by Lietze** [BP2022-AP1/bp2022-ap1#374]
## User stories
As a developer using the interlocking component I want the Railway Route Generator not to have endless recursion in order for the initialization to work and a Sumo config to be generated.

## References
- [Where the changes happend](https://github.com/BP2022-AP1/railway-route-generator/tree/refactor/replace-connected-nodes-edges)

## Acceptance Criteria
- [ ] The endless recursion is fixed

**Comment by SaturnHafen** [comment]
Please make sure that [this code](https://github.com/BP2022-AP1/bp2022-ap1/pull/375/files#diff-ae271df838b1aeaa3e5ac4fa36789cceac90c18379e212b78b81bb8609af853dR139-R144) is also un-mocked :)
