### ISSUE TITLE
Update the architecture diagram

### ISSUE THREAD

**Issue by Lietze** [BP2022-AP1/bp2022-ap1#39]
I have to rework the architecture diagram in order to acomondate the usage of the interlocking controller in our system

## References
- https://lucid.app/lucidchart/550dbdac-ddb5-42ea-a10d-1f1f890055e3/edit?viewport_loc=-993%2C-1448%2C6159%2C3046%2C0_0&invitationId=inv_889a89f3-3b13-4593-a419-76c9c2909f16

**Comment by CR1337** [comment]
Looks good to me. I approve.

Maybe the other team members should also have a look?
But as far as i am concerned you can close this.
