### ISSUE TITLE
Set-up & document branch protection

### ISSUE THREAD

**Issue by SaturnHafen** [BP2022-AP1/bp2022-ap1#4]
In order to aid a structured development process, we should add a `dev` branch, and apply branch protection to both the `dev` and the `main` branch. These should include forbidding direct pushes to these branches and require the pipeline to pass and at least 1 approving review.

The process should also be documented in the wiki.

**Comment by SaturnHafen** [comment]
See <https://github.com/BP2022-AP1/bp2022-ap1/settings/branches> and <https://github.com/BP2022-AP1/bp2022-ap1/wiki/Branch-protection>

**Comment by CR1337** [comment]
Looks reasonable to me.
