### ISSUE TITLE
Research how to avoid deadlocks when routing trains

### ISSUE THREAD

**Issue by Lietze** [BP2022-AP1/bp2022-ap1#419]
I have to research how to avoid deadlocks when routing trains in order to implement it later.

## (Wiki) References
- The results should be added to [this](https://github.com/BP2022-AP1/bp2022-ap1/wiki/Interlocking-Component) wiki page.

**Comment by CR1337** [comment]
I agree with your assessment that Dynamic Route Reservation would be the better fit for our project. An occurring deadlock would mean that the run it appeared in can not be evaluated. As an deadlock is by its nature unresolvable (without teleports or other magic) it would invalidate the run. In my opinion that's ok when it doesn't happen too often. We could then simply drop those runs when we have enough other runs that generate results for us.

Maybe this is something we could discuss in the whole team?

**Comment by Lietze** [comment]
We discussed it in the whole team and agreed, that Dynamic Route Reservation will be implemented. We will evaluate later whether there are too many deadlocks.
