### ISSUE TITLE
Update wiki and Diagrams

### ISSUE THREAD

**Issue by antonykamp** [BP2022-AP1/bp2022-ap1#428]
## User stories
As a developer, I want to have an up-to-date wiki to use it correctly and save.

## Acceptance Criteria
- [x] Read wiki
- [x] Update text
- [x] Update diagrams

**Comment by Lietze** [comment]
Is there a good way for me to review this issue? You may be the only one who knows what had to be changed and how the architecture evolved until now.

**Comment by antonykamp** [comment]
I know :) Maybe you just need to take a small look at https://github.com/BP2022-AP1/bp2022-ap1/wiki/Architecture 🙃 That should be enough.
