### ISSUE TITLE
Write documentation for EventBus alternatives

### ISSUE THREAD

**Issue by CR1337** [BP2022-AP1/bp2022-ap1#443]
In order to react to events that happen in the simulation we want to implement a system for distributing these events called `EventBus`. I want to present to alternative architectures in the Wiki.

## (Wiki) References
- [EventBus](https://github.com/BP2022-AP1/bp2022-ap1/wiki/EventBus)

**Comment by instant-sky** [comment]
Looks good to me, everything we discussed yesterday is in there! Thanks for writing it down neatly! I think the others should also have a look at it, because I already knew everything. 😇

**Comment by CR1337** [comment]
> Looks good to me, everything we discussed yesterday is in there! Thanks for writing it down neatly! I think the others should also have a look at it, because I already knew everything. innocent

@LucasDerReisende @SaturnHafen @antonykamp @Lietze

**Comment by antonykamp** [comment]
Diagrams ❤ 
I like the second proposal 🙃 The EventBus sounds pretty much like an observer pattern to me 😇 
I like the second approach. But couldn't be the Logger a Event Consumer too? 🤔 Looks like the EventDistributor and the EventBus do an equal thing. We can talk about it tomorrow.

**Comment by CR1337** [comment]
@antonykamp 
I added your suggestion to the wiki :)

**Comment by antonykamp** [comment]
Thanks 👍 Great work! Great diagrams 💚
