### ISSUE TITLE
Add functionality for `/component/fault-injection/platform-blocked-fault`

### ISSUE THREAD

**Issue by antonykamp** [BP2022-AP1/bp2022-ap1#449]
## User stories
As a user I want add a platform blocked fault configuration and get all my platofrm blocked fault configurations in order to administrate them.

## Dependencies
Depends on: 
 - #99 
 - #102 
 - #100 

## Acceptance Criteria
- [ ] Implement POST `/component/fault-injection/platoform-blocked-fault` path
- [ ] Implement GET `/component/fault-injection/platform-blocked-fault` path

**Comment by instant-sky** [comment]
duplicate of #446
