### ISSUE TITLE
Pass IInterlockingDisruptor to FaultInjectos

### ISSUE THREAD

**Issue by antonykamp** [BP2022-AP1/bp2022-ap1#522]
## User stories
As a developer of fault injectors, I want to use the functionality of the IInterlockingDisruptor to restart setting routes after injecting a fault. 

## Blocked by
- Add implementation of IInterlockingDisruptor

## Acceptance Criteria
- [ ] Pass Instance of IInterlockingDisruptor to FaultInjectos

**Comment by instant-sky** [comment]
This is not necessary anymore due to #521
