### ISSUE TITLE
Add skeleton of `ITraCICommunicator` interface 

### ISSUE THREAD

**Issue by antonykamp** [BP2022-AP1/bp2022-ap1#82]
## User stories
As a developer of the Implementor component I want to know the skeleton of the interface TraCICommunicator in order to use the TraCICommunicator component.

## (Wiki) References
- https://github.com/BP2022-AP1/bp2022-ap1/wiki/Architecture#tracicommunicator

## Acceptance Criteria
- [x] Add ITraCICommunicator 
- [x] Update wiki

**Comment by SaturnHafen** [comment]
This already exists [here](https://github.com/BP2022-AP1/bp2022-ap1/blob/dev/src/wrapper/communicator.py).
Should we move it to a new directory? @antonykamp

**Comment by antonykamp** [comment]
> Should we move it to a new directory? @antonykamp

The advantage would be that the folders would reflect the division into components.  On the other hand, it currently corresponds to the division of tasks among the developers, which is also not bad.
