### ISSUE TITLE
Add skeleton of `IAnalysisResult` interface

### ISSUE THREAD

**Issue by antonykamp** [BP2022-AP1/bp2022-ap1#83]
## User stories
As a developer of the Implementor component I want to know the skeleton of the interface IAnalysisResult in order to use the DataScience component.

## (Wiki) References
- https://github.com/BP2022-AP1/bp2022-ap1/wiki/Architecture#datascience

## Acceptance Criteria
- [ ] Add IAnalysisResult

**Comment by LucasDerReisende** [comment]
Not needed anymore since #344 implements data science results
