### ISSUE TITLE
Add skeleton of `IAnalysisCalculation` interface

### ISSUE THREAD

**Issue by antonykamp** [BP2022-AP1/bp2022-ap1#84]
## User stories
As a developer of the TraCICommunicator component I want to know the skeleton of the interface IAnalysisCalculator in order to use the DataScience component.

## (Wiki) References
- https://github.com/BP2022-AP1/bp2022-ap1/wiki/Architecture#datascience

## Acceptance Criteria
- [ ] Add IAnalysisCalculator
- [ ] Update wiki

**Comment by LucasDerReisende** [comment]
Not needed anymore since #344 implements data science results and no interface to traci communicator needed
