### ISSUE TITLE
Add skeleton of `ILogCollector` interface

### ISSUE THREAD

**Issue by antonykamp** [BP2022-AP1/bp2022-ap1#85]
## User stories
As a developer of the DataScience component I want to know the skeleton of the interface ILogCollector in order to use the Logger component.

## (Wiki) References
- https://github.com/BP2022-AP1/bp2022-ap1/wiki/Architecture#logger

## Acceptance Criteria
- [x] Add ILogCollector
- [x] Update wiki

**Comment by LucasDerReisende** [comment]
Duplicate with #319

**Comment by LucasDerReisende** [comment]
Closed with #319
